name: "Seasonal post action"
author: "@katydecorah"
description: "Generate a season post from Jekyll data file."
runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  GitHubUsername:
    description: The GitHub username that owns the repository with the data files.
    required: true
  GitHubRepository:
    description: The Github repository that has the data files.
    required: true
  SeasonNames:
    description: The season names in order by the season that ends in March, June, September, and then December.
    default: "Winter,Spring,Summer,Fall"
  SeasonEmoji:
    description: Emoji to assign each season in the same order as described by `SeasonNames`.
    default: "❄️,🌷,☀️,🍂"
  PostsDir:
    description: The path to where you want to save your seasonal post files to in this repository.
    default: "notes/_posts/"
  SeasonalPostTemplate:
    description: The path to the template file for the seasonal post.
    default: ".github/actions/seasonal-post-template.md"
