name: "Seasonal post action"
author: "@katydecorah"
description: "A GitHub action that creates a seasonal post from data files."
runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  GitHubUsername:
    description: The GitHub username that owns the repository with the data files.
    required: true
  GitHubRepository:
    description: The Github repository that has the data files.
    required: true
  SeasonNames:
    description: The season names in order by the season that ends in March, June, September, and then December.
    default: "Winter,Spring,Summer,Fall"
  SeasonEmoji:
    description: Emoji to assign each season in the same order as described by `SeasonNames`.
    default: "❄️,🌷,☀️,🍂"
  PostsDir:
    description: The path to where you want to save your seasonal post files to in this repository.
    default: "notes/_posts/"
  SeasonalPostTemplate:
    description: "If you'd like to customize the [markdown template](src/template.md), define a path to your own. Example: `SeasonalPostTemplate: .github/actions/seasonal-post-template.md`. The markdown template shows all the available variables and an idea for how you may want to format this file. For now, the templating is simplistic and does not offer functionality outside of this action replacing variable names."
