import { readFileSync } from "fs";
import { formatBooks, formatPlaylist, formatBookmarks } from "../format";

const recipes = JSON.parse(
  readFileSync("./src/__tests__/fixtures/recipes.json", "utf-8")
);

export const { bookmarks } = formatBookmarks({
  bookmarkData: recipes,
  start: "2021-09-21",
  end: "2021-12-20",
});

it("bookmarks", () => {
  expect(bookmarks).toMatchInlineSnapshot(`
    [
      {
        "date": "2021-09-21",
        "description": "Gyeran bap is a lifesaving Korean pantry meal of fried eggs stirred into steamed white rice In this version, the eggs fry and puff up slightly in a shallow bath of browned butter Soy sauce, which reduces in the pan, seasons the rice, as does a final smattering of salty gim, or roasted seaweed",
        "notes": "⭐️⭐️⭐️⭐️⭐️",
        "site": "NYT Cooking",
        "title": "Gyeran Bap (Egg Rice) Recipe",
        "url": "https://cooking.nytimes.com/recipes/1022530-gyeran-bap-egg-rice",
      },
      {
        "date": "2021-09-25",
        "description": "A delightful breakfast, these burritos filled with soft scrambled eggs, scallion-flecked refried beans and buttery avocado slices are also great any time of the day Cilantro adds freshness, and a few drops of your favorite hot sauce will deliver a nice zing The nontraditional open-ended rolling technique used here will tightly encase the filling in the smaller-sized tortillas while ensuring the optimal tortilla-to-stuffing ratio",
        "site": "NYT Cooking",
        "title": "Breakfast Burritos Recipe",
        "url": "https://cooking.nytimes.com/recipes/1022540-breakfast-burritos",
      },
      {
        "date": "2021-10-11",
        "description": "This is a classic, comforting pot roast, rich with red wine and onions A pressure cooker works wonders on tough cuts of meat like the chuck roast called for here; the roast is braised to tenderness in a fraction of the time it would take in the oven The trick to this perfectly cooked meal is timing: Pop the vegetables into the pressure cooker just for the last few minutes of cooking, so they are tender but not overly softened",
        "image": "bookmark-pressure-cooker-pot-roast-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Pressure Cooker Pot Roast Recipe",
        "url": "https://cooking.nytimes.com/recipes/1020846-pressure-cooker-pot-roast",
      },
      {
        "date": "2021-10-12",
        "description": "Applesauce isn’t just for babies Sure, this very basic version is perfect for tender palates, but it also works as the base for many a sweet treat In the fall you might try swapping in 1 1/2 pounds of pears for half of the apples and a bit of caramel in place of the maple",
        "image": "bookmark-cinnamon-maple-applesauce-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Cinnamon-Maple Applesauce Recipe",
        "url": "https://cooking.nytimes.com/recipes/1022568-cinnamon-maple-applesauce",
      },
      {
        "date": "2021-10-17",
        "description": "Many apple pies call for simply tossing cut apples with sugar, adding a thickening agent and some spices, and plopping it all into a crust But precooking the apples has multiple advantages: First, it draws out some of their juices, to ensure consistency (No undercooked apples or runny filling here!) And, second, it prevents the filling from sinking away from the crust as it cools, leaving a pocket of air between filling and crust",
        "image": "bookmark-apple-pie-filling-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Apple Pie Filling Recipe",
        "url": "https://cooking.nytimes.com/recipes/1021576-apple-pie-filling",
      },
      {
        "date": "2021-10-17",
        "description": "This classic dough contains no special ingredients, just flour, salt, butter and water, but it works like a dream The recipe makes a single crust for a 9-inch pie; simply double it to make a double-crust pie (If you make it by hand, you can even triple or quadruple the recipe.) If you’d prefer to use a food processor, you can, and it’s a good idea if you have warm hands",
        "image": "bookmark-perfect-pie-crust-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Perfect Pie Crust Recipe",
        "url": "https://cooking.nytimes.com/recipes/1019713-perfect-pie-crust",
      },
      {
        "date": "2021-10-23",
        "description": "This elegant riff on a childhood favorite came to The Times in 2009 by way of Jamie Oliver, the British chef and cookbook author It was featured in his cookbook “Jamie’s Food Revolution: Rediscover How to Cook Simple, Delicious, Affordable Meals," and it's a favorite of his daughters, Poppy and Daisy It's wholesome (no powdered cheese!), and it can be ready in about 15 minutes.",
        "image": "bookmark-creamy-pasta-with-smoked-bacon-and-peas-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Creamy Pasta With Smoked Bacon and Peas Recipe",
        "url": "https://cooking.nytimes.com/recipes/1012805-creamy-pasta-with-smoked-bacon-and-peas",
      },
      {
        "date": "2021-11-14",
        "description": "Pancakes are so easy to make that they encourage experimentation Enter this cornmeal-blueberry variation, which feels like a weekend treat but is well suited for the weekday morning rush Here, 1/2 cup of cornmeal is swapped out for a portion of the all-purpose flour, giving the pancake a wonderful texture",
        "image": "bookmark-cornmeal-blueberry-pancakes-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Cornmeal-Blueberry Pancakes Recipe",
        "url": "https://cooking.nytimes.com/recipes/1018177-cornmeal-blueberry-pancakes",
      },
      {
        "date": "2021-11-28",
        "description": "Honey, lemon zest and poppy seeds are stirred into a batter enriched with Greek yogurt elevating the pancake from typical to terrific With a scoop of ice cream, these could more than pass for dessert.",
        "image": "bookmark-lemon-poppy-seed-pancakes-with-greek-yogurt-and-jam-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Lemon Poppy-Seed Pancakes with Greek Yogurt and Jam Recipe",
        "url": "https://cooking.nytimes.com/recipes/12417-lemon-poppy-seed-pancakes-with-greek-yogurt-and-jam",
      },
      {
        "date": "2021-11-28",
        "description": "The German-style potato salad doesn’t contain any mayonnaise, but is rich with bacon, whole-grain mustard and sweet fried shallots It’s best served warm while the bacon still glistens with fat, but is also nice at room temperature Make it as close to serving time as possible",
        "image": "bookmark-bacon-and-shallot-potato-salad-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Bacon and Shallot Potato Salad Recipe",
        "url": "https://cooking.nytimes.com/recipes/1017404-bacon-and-shallot-potato-salad",
      },
      {
        "date": "2021-11-28",
        "description": "This simple, bright green bean dish is as welcome alongside weeknight salmon as it is a Thanksgiving turkey Green beans are delicious roasted at a high temperature and take just 15 minutes to cook, which particularly important on Thanksgiving when oven space is precious Trim the green beans ahead of time, and this dish will come together in a flash",
        "image": "bookmark-roasted-green-beans-with-pancetta-and-lemon-zest-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Roasted Green Beans With Pancetta and Lemon Zest Recipe",
        "url": "https://cooking.nytimes.com/recipes/1020573-roasted-green-beans-with-pancetta-and-lemon-zest",
      },
      {
        "date": "2021-11-28",
        "description": "Pointedly low-fuss and remarkably moist, this recipe gets its verve from pickles used two ways: Dill pickle brine seasons and moistens the chicken from the inside-out, while chopped pickles add zip to the coleslaw Many fried chicken sandwich recipes use breasts, but thighs have more fat, which means they’re more flavorful and harder to overcook The chicken also fries at a lower temperature, so it finishes cooking and its crust crisps at precisely the same time. The buttermilk is key to the crispness here, so avoid any substitutions",
        "image": "bookmark-pickle-brined-fried-chicken-sandwich-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Pickle-Brined Fried Chicken Sandwich Recipe",
        "url": "https://cooking.nytimes.com/recipes/1020385-pickle-brined-fried-chicken-sandwich",
      },
      {
        "date": "2021-11-28",
        "description": "Vietnamese-style marinated pork chops are often served whole with rice noodles, herbs and a dipping sauce This version mixes all the components, infusing the noodles, sliced meat and vegetables with the sauce and keeping the noodles tender even after a day in the fridge Dark, robust maple syrup takes the place of the traditional dark caramel in a nod to autumn (and as a weeknight shortcut to save you the hassle of browning sugar)",
        "image": "bookmark-rice-noodles-with-seared-pork-carrots-and-herbs-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Rice Noodles With Seared Pork, Carrots and Herbs Recipe",
        "url": "https://cooking.nytimes.com/recipes/1019646-rice-noodles-with-seared-pork-carrots-and-herbs",
      },
      {
        "date": "2021-12-05",
        "description": "It’s no wonder pancakes are a weekend staple: Their batter comes together in just 5 minutes using ingredients you’re likely to have on hand Here, ground cardamom and fresh orange zest provide an aromatic boost that is sweet and addictive, but subtle enough that you can still pair your pancakes with any typical accompaniments The recipe is plentiful enough for 12 full-size pancakes, or twice the number of mini pancakes if preparing brunch for a crowd",
        "image": "bookmark-orange-cardamom-pancakes-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Orange-Cardamom Pancakes Recipe",
        "url": "https://cooking.nytimes.com/recipes/1019947-orange-cardamom-pancakes",
      },
      {
        "date": "2021-12-06",
        "description": "Here’s a recipe for when you want towering, fluffy biscuits, but don’t want a large batch You can use pretty much any ovenproof dish — a baking sheet, a square or round cake pan, or even a skillet — but be sure to butter the pan beforehand If you like things a little less seasoned, reduce the salt to 1/2 teaspoon, and if you use salted butter in the dough, reduce the salt to 1/4 teaspoon",
        "image": "bookmark-small-batch-buttermilk-biscuits-recipe.jpg",
        "notes": "⭐️⭐️⭐️⭐️⭐️",
        "site": "NYT Cooking",
        "title": "Small-Batch Buttermilk Biscuits Recipe",
        "url": "https://cooking.nytimes.com/recipes/1021862-small-batch-buttermilk-biscuits",
      },
      {
        "date": "2021-12-09",
        "description": "You might think fajitas are too fussy for a weeknight, but this easy, foolproof version roasts on a sheet pan and can be ready in an hour Because the ingredients are thinly sliced, everything cooks in a flash — and with little attention required Smoked paprika, chipotle chiles and a quick stop under the broiler provide the smoky flavor that would traditionally come from the grill",
        "image": "bookmark-sheet-pan-chicken-fajitas-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Sheet-Pan Chicken Fajitas Recipe",
        "url": "https://cooking.nytimes.com/recipes/1020092-sheet-pan-chicken-fajitas",
      },
      {
        "date": "2021-12-11",
        "description": "In this easy chicken stir-fry, adapted from Lan Hing Riggin, a home cook from Virginia who grew up cooking with her family in Hong Kong, slivers of ginger and scallions turn golden, adding their sweetness and pungency to the oil A dash of soy sauce provides saltiness and depth, while a full cup of cilantro leaves, used as garnish, makes the dish a bit lighter and fresher Fire seekers can add a sliced chile or two along with the ginger.",
        "image": "bookmark-ginger-scallion-chicken-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Ginger-Scallion Chicken Recipe",
        "url": "https://cooking.nytimes.com/recipes/1019283-ginger-scallion-chicken",
      },
      {
        "date": "2021-12-13",
        "description": "Chicken meatballs may not be a traditionally Moroccan dish, but they work beautifully when spiced with paprika, cumin, cinnamon, ginger and garlic, which are commonly found in the country’s cuisine Whole-milk yogurt does double duty here: It’s used to make the meatballs moist and tender, and makes for a speedy sauce to serve with them Don’t use ground chicken made with ultralean breasts; look for labels that show a mix of white and dark meat",
        "image": "bookmark-moroccan-spiced-chicken-meatballs-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Moroccan-Spiced Chicken Meatballs Recipe",
        "url": "https://cooking.nytimes.com/recipes/1022719-moroccan-spiced-chicken-meatballs",
      },
      {
        "date": "2021-12-18",
        "description": "While stir-fries have long gone hand-in-hand with rice, this recipe shows the versatility of the dish Here, a quick stir-fry is transformed into a flavorful, unconventional pasta sauce Five spice is a Chinese seasoning that is said to incorporate all five tastes: sweet, sour, bitter, salty and umami",
        "image": "bookmark-mushroom-pasta-stir-fry-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Mushroom Pasta Stir-Fry Recipe",
        "url": "https://cooking.nytimes.com/recipes/1022121-mushroom-pasta-stir-fry",
      },
      {
        "date": "2021-12-18",
        "description": "Schnitzel is a way of preparing thin slices of meat by breading and frying them until crisp While the popular Viennese dish is traditionally made with thinly pounded veal, here, pounded pork cutlets are breaded and baked on a sheet pan — rather than fried in a skillet — until golden for an easy weeknight meal The key to perfectly brown breadcrumbs is the addition of a few dollops of mayonnaise, which helps the coating crisp up during baking",
        "image": "bookmark-sheet-pan-crispy-pork-schnitzel-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Sheet-Pan Crispy Pork Schnitzel Recipe",
        "url": "https://cooking.nytimes.com/recipes/1022582-sheet-pan-crispy-pork-schnitzel",
      },
      {
        "date": "2021-12-19",
        "description": "Everyone needs a good sugar cookie recipe If you can master the very simple technique behind this one dough, you have several variations at your disposal, most likely without a trip to the grocery store.",
        "image": "bookmark-sugar-cookies-recipe.jpg",
        "site": "NYT Cooking",
        "title": "Sugar Cookies Recipe",
        "url": "https://cooking.nytimes.com/recipes/1018383-sugar-cookies",
      },
      {
        "date": "2021-12-19",
        "description": "Royal icing is the classic sweet glue that holds together gingerbread houses and provides a glossy medium for elaborate cookie decorations Many recipes call for egg whites or cream of tartar or both, but meringue powder (available online or at specialty food stores) offers gloss, stability and creaminess without the use of raw eggs or other ingredients This recipe was developed by Georganne Bell, a professional cookie-decorating teacher in Salt Lake City who doesn’t like traditional vanilla sugar cookies",
        "image": "bookmark-the-fluffiest-royal-icing-recipe.jpg",
        "site": "NYT Cooking",
        "title": "The Fluffiest Royal Icing Recipe",
        "url": "https://cooking.nytimes.com/recipes/1019785-the-fluffiest-royal-icing",
      },
    ]
  `);
});

const playlistData = JSON.parse(
  readFileSync("./src/__tests__/fixtures/playlists.json", "utf-8")
);

export const { playlist } = formatPlaylist({
  playlistData,
  name: "2021 Fall",
});

it("playlist", () => {
  expect(playlist).toMatchInlineSnapshot(`
    {
      "playlist": "2021 Fall",
      "spotify": "https://open.spotify.com/playlist/2YnPs9UNBkJpswmsRNwQ1o",
      "tracks": [
        {
          "album": "one hand on the steering wheel the other sewing a garden",
          "artist": "Ada Lea",
          "track": "can't stop me from dying",
        },
        {
          "album": "No Shadow",
          "artist": "Hyd",
          "track": "No Shadow",
        },
        {
          "album": "Trip To Japan",
          "artist": "The Shacks",
          "track": "Trip To Japan",
        },
        {
          "album": "Keeper",
          "artist": "Hana Vu",
          "track": "Maker",
        },
        {
          "album": "Doomin' Sun",
          "artist": "Bachelor, Jay Som, Palehound",
          "track": "Anything at All",
        },
        {
          "album": "Would You Mind Please Pulling Me Close?",
          "artist": "Tasha",
          "track": "Would You Mind Please Pulling Me Close?",
        },
        {
          "album": "Genesis",
          "artist": "Spencer.",
          "track": "Genesis",
        },
        {
          "album": "Old Peel",
          "artist": "Aldous Harding",
          "track": "Old Peel",
        },
        {
          "album": "Everybody's Birthday",
          "artist": "Hana Vu",
          "track": "Everybody's Birthday",
        },
        {
          "album": "The Baby",
          "artist": "Samia",
          "track": "Big Wheel",
        },
        {
          "album": "-io",
          "artist": "Circuit des Yeux",
          "track": "Dogma",
        },
        {
          "album": "private LIFE",
          "artist": "Virginia Wing",
          "track": "I'm Holding Out For Something",
        },
        {
          "album": "Blue Weekend",
          "artist": "Wolf Alice",
          "track": "Delicious Things",
        },
        {
          "album": "Bottle Episode",
          "artist": "Mandy, Indiana",
          "track": "Bottle Episode",
        },
        {
          "album": "The Gaping Mouth",
          "artist": "Lowertown",
          "track": "The Gaping Mouth",
        },
        {
          "album": "Fantasize Your Ghost",
          "artist": "Ohmme",
          "track": "3 2 4 3",
        },
        {
          "album": "You Think It's Like This But Really It's Like This",
          "artist": "Mirah",
          "track": "Of Pressure",
        },
        {
          "album": "When the Sun Comes Up",
          "artist": "Greta Morgan",
          "track": "When the Sun Comes Up",
        },
        {
          "album": "Ceremony",
          "artist": "Anna von Hausswolff",
          "track": "Mountains Crave",
        },
      ],
    }
  `);
});

const bookData = JSON.parse(
  readFileSync("./src/__tests__/fixtures/books.json", "utf-8")
);

export const { books } = formatBooks({
  bookData,
  start: "2021-09-21",
  end: "2021-12-20",
});

it("books", () => {
  expect(books).toMatchInlineSnapshot(`
    [
      {
        "authors": "Emily Henry",
        "categories": [
          "FICTION",
        ],
        "dateFinished": "2021-09-24",
        "description": "When Poppy met Alex, there was no spark, no chemistry, and no reason to think they'd ever talk again. Alex is quiet, studious, and destined for a future in academia. Poppy is a wild child who only came to U of Chicago to escape small-town life. But after sharing a ride home for the summer, the two form a surprising friendship. After all, who better to confide in than someone you could never, ever date? Over the years, Alex and Poppy's lives take them in different directions, but every summer the two find their way back to each other for a magical weeklong vacation. Until one trip goes awry, and in the fallout, they lose touch. Now, two years later, Poppy's in a rut. Her dream job, her relationships, her life--none of it is making her happy. In fact, the last time she remembers feeling truly happy was on that final, ill-fated Summer Trip. The answer to all her problems is obvious: She needs one last vacation to win back her best friend. As a hilariously disastrous week unfolds and tensions rise, Poppy and Alex are forced to confront what drove them apart--and decide what they're willing to risk for the chance to be together…",
        "isbn": "9781984806758",
        "language": "en",
        "link": "https://books.google.com/books/about/People_We_Meet_on_Vacation.html?hl=&id=5fooEAAAQBAJ",
        "pageCount": 384,
        "printType": "BOOK",
        "publishedDate": "2021",
        "thumbnail": "https://books.google.com/books/content?id=5fooEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "People We Meet on Vacation",
        "url": "https://books.google.com/books/about/People_We_Meet_on_Vacation.html?hl=&id=5fooEAAAQBAJ",
      },
      {
        "authors": "Sally Rooney",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-09-30",
        "description": "Beautiful World, Where Are You is a new novel by Sally Rooney, the bestselling author of Normal People and Conversations with Friends. Alice, a novelist, meets Felix, who works in a warehouse, and asks him if he’d like to travel to Rome with her. In Dublin, her best friend, Eileen, is getting over a break-up, and slips back into flirting with Simon, a man she has known since childhood. Alice, Felix, Eileen, and Simon are still young—but life is catching up with them. They desire each other, they delude each other, they get together, they break apart. They have sex, they worry about sex, they worry about their friendships and the world they live in. Are they standing in the last lighted room before the darkness, bearing witness to something? Will they find a way to believe in a beautiful world?",
        "isbn": "9780374602611",
        "language": "en",
        "link": "https://play.google.com/store/books/details?id=sL4SEAAAQBAJ",
        "pageCount": 368,
        "printType": "BOOK",
        "publishedDate": "2021-09-07",
        "thumbnail": "https://books.google.com/books/content?id=sL4SEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Beautiful World, Where Are You",
        "url": "https://play.google.com/store/books/details?id=sL4SEAAAQBAJ",
      },
      {
        "authors": "Akwaeke Emezi",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-10-07",
        "description": "A National Book Foundation “5 Under 35” Honoree Finalist for the PEN/Hemingway Award for a Debut Novel Shortlisted for the Center for Fiction First Novel Prize A New York Times Notable Book One of the most highly praised novels of the year, the debut from an astonishing young writer, Freshwater tells the story of Ada, an unusual child who is a source of deep concern to her southern Nigerian family. Young Ada is troubled, prone to violent fits. Born “with one foot on the other side,” she begins to develop separate selves within her as she grows into adulthood. And when she travels to America for college, a traumatic event on campus crystallizes the selves into something powerful and potentially dangerous, making Ada fade into the background of her own mind as these alters—now protective, now hedonistic—move into control. Written with stylistic brilliance and based in the author’s realities, Freshwater dazzles with ferocious energy and serpentine grace.",
        "isbn": "9780802165565",
        "language": "en",
        "link": "https://play.google.com/store/books/details?id=_eUoDwAAQBAJ",
        "pageCount": 240,
        "printType": "BOOK",
        "publishedDate": "2018-02-13",
        "thumbnail": "https://books.google.com/books/content?id=_eUoDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Freshwater",
        "url": "https://play.google.com/store/books/details?id=_eUoDwAAQBAJ",
      },
      {
        "authors": "Donika Kelly",
        "categories": [
          "Poetry",
        ],
        "dateFinished": "2021-10-07",
        "description": "An extraordinary collection of endurance and transformation by the award-winning author of Bestiary The Renunciations is a book of resilience, survival, and the journey to radically shift one’s sense of self in the face of trauma. Moving between a childhood marked by love and abuse and the breaking marriage of that adult child, Donika Kelly charts memory and the body as landscapes to be traversed and tended. These poems construct life rafts and sanctuaries even in their most devastating confrontations with what a person can bear, with how families harm themselves. With the companionship of “the oracle”—an observer of memory who knows how each close call with oblivion ends—the act of remembrance becomes curative, and personal mythologies give way to a future defined less by wounds than by possibility. In this gorgeous and heartrending second collection, we find the home one builds inside oneself after reckoning with a legacy of trauma—a home whose construction starts “with a razing.”",
        "isbn": "9781644450536",
        "language": "en",
        "link": "https://books.google.com/books/about/The_Renunciations.html?hl=&id=_xC-zQEACAAJ",
        "pageCount": 72,
        "printType": "BOOK",
        "publishedDate": "2021-05-04",
        "thumbnail": "https://books.google.com/books/content?id=_xC-zQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "title": "The Renunciations",
        "url": "https://books.google.com/books/about/The_Renunciations.html?hl=&id=_xC-zQEACAAJ",
      },
      {
        "authors": "Helen Hoang",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-10-11",
        "description": "USA Today bestselling author Helen Hoang returns with a witty and sizzling new romance that shows how wrong you can be about someone...and how right they can be for you. To most people, Quan Diep is nothing but a surly-looking, underachieving playboy. The problem is he's not any of those things. And now that he's the CEO of an up-and-coming retail business, he's suddenly a "catch," and the rich girls who never used to pay any attention to him are looking at him in a new way--especially Camilla, the girl who brushed him off many years ago. Anna Sun dislikes Quan Diep almost as much as germy bathroom door handles. Or so she tells herself. She will never admit that she has a secret crush on him, especially because he only has eyes for her charismatic and newly engaged younger sister Camilla. Over the years, Anna has worked hard to overcome her OCD, but she'll still need to find a way to bury her anxieties and seduce Quan so he doesn't ruin her sister's engagement, and with it, a crucial real estate development deal. Slowly, Anna breaks down Quan's dangerous and careless exterior while peeling off her own tough, protective shell. But when Quan discovers Anna's true intentions, he's forced to confront his own hurtful past and learn to forgive, while Anna must face her greatest challenge: truly opening herself up to love.",
        "isbn": "9780593197837",
        "language": "en",
        "link": "https://books.google.com/books/about/The_Heart_Principle.html?hl=&id=fzc7EAAAQBAJ",
        "pageCount": 352,
        "printType": "BOOK",
        "publishedDate": "2021",
        "thumbnail": "https://books.google.com/books/content?id=fzc7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "The Heart Principle",
        "url": "https://books.google.com/books/about/The_Heart_Principle.html?hl=&id=fzc7EAAAQBAJ",
      },
      {
        "authors": "Ottessa Moshfegh",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-10-16",
        "description": "Dreaming of life in the city while caring for her alcoholic father and working in a 1960s boys' prison, a disturbed young woman is manipulated into committing a psychologically charged crime during the holiday season.",
        "isbn": "9780143128755",
        "language": "en",
        "link": "https://books.google.com/books/about/Eileen.html?hl=&id=AKqvDAAAQBAJ",
        "pageCount": 260,
        "printType": "BOOK",
        "publishedDate": "2016",
        "thumbnail": "https://books.google.com/books/content?id=AKqvDAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Eileen",
        "url": "https://books.google.com/books/about/Eileen.html?hl=&id=AKqvDAAAQBAJ",
      },
      {
        "authors": "Amir Levine, Rachel Heller",
        "categories": [
          "Self-Help",
        ],
        "dateFinished": "2021-10-23",
        "description": "Introduces the theory of adult attachment as an advanced relationship science that can enable individuals to find and sustain love, offering insight into the roles of genetics and early family life in how people approach relationships.",
        "isbn": "9781585429134",
        "language": "en",
        "link": "https://books.google.com/books/about/Attached.html?hl=&id=_O0oDwAAQBAJ",
        "pageCount": 294,
        "printType": "BOOK",
        "publishedDate": "2011",
        "thumbnail": "https://books.google.com/books/content?id=_O0oDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Attached",
        "url": "https://books.google.com/books/about/Attached.html?hl=&id=_O0oDwAAQBAJ",
      },
      {
        "authors": "Shirley Jackson",
        "categories": null,
        "dateFinished": "2021-10-27",
        "description": "An anthropologist conducts an unusual research project in a reputedly haunted house",
        "isbn": "9780606415545",
        "language": "en",
        "link": "https://books.google.com/books/about/The_Haunting_of_Hill_House.html?hl=&id=8v3mwAEACAAJ",
        "pageCount": 208,
        "printType": "BOOK",
        "publishedDate": "2006-11-28",
        "thumbnail": "https://books.google.com/books/content?id=8v3mwAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "title": "The Haunting of Hill House",
        "url": "https://books.google.com/books/about/The_Haunting_of_Hill_House.html?hl=&id=8v3mwAEACAAJ",
      },
      {
        "authors": "Rumaan Alam",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-11-01",
        "description": "A Read with Jenna Today Show Book Club Pick! Finalist for the 2020 National Book Award (Fiction) A Best Book of the Year From: The Washington Post * Time * NPR * Elle * Esquire * Kirkus * Library Journal * The Chicago Public Library * The New York Public Library * BookPage * The Globe and Mail * EW.com * The LA Times * USA Today * InStyle * The New Yorker * AARP * Publisher's Lunch * LitHub * Book Marks * Electric Literature * Brooklyn Based * The Boston Globe A magnetic novel about two families, strangers to each other, who are forced together on a long weekend gone terribly wrong. From the bestselling author of Rich and Pretty comes a suspenseful and provocative novel keenly attuned to the complexities of parenthood, race, and class. Leave the World Behind explores how our closest bonds are reshaped—and unexpected new ones are forged—in moments of crisis. Amanda and Clay head out to a remote corner of Long Island expecting a vacation: a quiet reprieve from life in New York City, quality time with their teenage son and daughter, and a taste of the good life in the luxurious home they’ve rented for the week. But a late-night knock on the door breaks the spell. Ruth and G. H. are an older couple—it’s their house, and they’ve arrived in a panic. They bring the news that a sudden blackout has swept the city. But in this rural area—with the TV and internet now down, and no cell phone service—it’s hard to know what to believe. Should Amanda and Clay trust this couple—and vice versa? What happened back in New York? Is the vacation home, isolated from civilization, a truly safe place for their families? And are they safe from one other?",
        "isbn": "9780062667656",
        "language": "en",
        "link": "https://play.google.com/store/books/details?id=UyTIDwAAQBAJ",
        "pageCount": 256,
        "printType": "BOOK",
        "publishedDate": "2020-10-06",
        "thumbnail": "https://books.google.com/books/content?id=UyTIDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Leave the World Behind",
        "url": "https://play.google.com/store/books/details?id=UyTIDwAAQBAJ",
      },
      {
        "authors": "Jonny Sun",
        "categories": [
          "Literary Collections",
        ],
        "dateFinished": "2021-11-02",
        "description": "Instant New York Times Bestseller “Truly, there's no shame in taking a break from books during the pandemic. But if you're feeling ready to reach out, try starting with Goodbye, Again. Take my word for it — let Jonny Sun into your life.”---Janet W. Lee, NPR The wonderfully original author of Everyone's a Aliebn When Ur a Aliebn Too gives us a collection of touching and hilarious personal essays, stories, poems—accompanied by his trademark illustrations—covering topics such as mental health, happiness, and what it means to belong. Jonny Sun is back with a collection of essays and other writings in his unique, funny, and heartfelt style. The pieces range from long meditations on topics like loneliness and being an outsider, to short humor pieces, conversations, and memorable one-liners. Jonny's honest writings about his struggles with feeling productive, as well as his difficulties with anxiety and depression will connect deeply with his fans as well as anyone attempting to create in our chaotic world. It also features a recipe for scrambled eggs that might make you cry.",
        "isbn": "9780062880864",
        "language": "en",
        "link": "https://play.google.com/store/books/details?id=MWinDwAAQBAJ",
        "pageCount": 240,
        "printType": "BOOK",
        "publishedDate": "2021-04-20",
        "thumbnail": "https://books.google.com/books/content?id=MWinDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Goodbye, Again",
        "url": "https://play.google.com/store/books/details?id=MWinDwAAQBAJ",
      },
      {
        "authors": "Judson Brewer",
        "categories": [
          "Self-Help",
        ],
        "dateFinished": "2021-11-09",
        "description": "The instant New York Times bestseller A step-by-step plan clinically proven to break the cycle of worry and fear that drives anxiety and addictive habits We are living through one of the most anxious periods any of us can remember. Whether facing issues as public as a pandemic or as personal as having kids at home and fighting the urge to reach for the wine bottle every night, we are feeling overwhelmed and out of control. But in this timely book, Judson Brewer explains how to uproot anxiety at its source using brain-based techniques and small hacks accessible to anyone. We think of anxiety as everything from mild unease to full-blown panic. But it's also what drives the addictive behaviors and bad habits we use to cope (e.g. stress eating, procrastination, doom scrolling and social media). Plus, anxiety lives in a part of the brain that resists rational thought. So we get stuck in anxiety habit loops that we can't think our way out of or use willpower to overcome. Dr. Brewer teaches us map our brains to discover our triggers, defuse them with the simple but powerful practice of curiosity, and to train our brains using mindfulness and other practices that his lab has proven can work. Distilling more than 20 years of research and hands-on work with thousands of patients, including Olympic athletes and coaches, and leaders in government and business, Dr. Brewer has created a clear, solution-oriented program that anyone can use to feel better - no matter how anxious they feel.",
        "isbn": "9780593330456",
        "language": "en",
        "link": "https://play.google.com/store/books/details?id=GxACEAAAQBAJ",
        "pageCount": 304,
        "printType": "BOOK",
        "publishedDate": "2021-03-09",
        "thumbnail": "https://books.google.com/books/content?id=GxACEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Unwinding Anxiety",
        "url": "https://play.google.com/store/books/details?id=GxACEAAAQBAJ",
      },
      {
        "authors": "Cherie Dimaline",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-11-17",
        "description": "“Deftly written, gripping and informative. Empire of Wild is a rip-roaring read!”—Margaret Atwood, From Instagram “Empire of Wild is doing everything I love in a contemporary novel and more. It is tough, funny, beautiful, honest and propulsive—all the while telling a story that needs to be told by a person who needs to be telling it.”—Tommy Orange, author of There There A bold and brilliant new indigenous voice in contemporary literature makes her American debut with this kinetic, imaginative, and sensuous fable inspired by the traditional Canadian Métis legend of the Rogarou—a werewolf-like creature that haunts the roads and woods of native people’s communities. Joan has been searching for her missing husband, Victor, for nearly a year—ever since that terrible night they’d had their first serious argument hours before he mysteriously vanished. Her Métis family has lived in their tightly knit rural community for generations, but no one keeps the old ways . . . until they have to. That moment has arrived for Joan. One morning, grieving and severely hungover, Joan hears a shocking sound coming from inside a revival tent in a gritty Walmart parking lot. It is the unmistakable voice of Victor. Drawn inside, she sees him. He has the same face, the same eyes, the same hands, though his hair is much shorter and he's wearing a suit. But he doesn't seem to recognize Joan at all. He insists his name is Eugene Wolff, and that he is a reverend whose mission is to spread the word of Jesus and grow His flock. Yet Joan suspects there is something dark and terrifying within this charismatic preacher who professes to be a man of God . . . something old and very dangerous. Joan turns to Ajean, an elderly foul-mouthed card shark who is one of the few among her community steeped in the traditions of her people and knowledgeable about their ancient enemies. With the help of the old Métis and her peculiar Johnny-Cash-loving, twelve-year-old nephew Zeus, Joan must find a way to uncover the truth and remind Reverend Wolff who he really is . . . if he really is. Her life, and those of everyone she loves, depends upon it.",
        "isbn": "9780062975966",
        "language": "en",
        "link": "https://play.google.com/store/books/details?id=O5K5DwAAQBAJ",
        "pageCount": 320,
        "printType": "BOOK",
        "publishedDate": "2020-07-28",
        "thumbnail": "https://books.google.com/books/content?id=O5K5DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Empire of Wild",
        "url": "https://play.google.com/store/books/details?id=O5K5DwAAQBAJ",
      },
      {
        "authors": "Emily Henry",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-11-25",
        "description": ""A romance writer who no longer believes in love and a literary writer stuck in a rut engage in a summer-long challenge that may just upend everything they believe about happily ever afters. Augustus Everett is an acclaimed author of literary fiction. January Andrews writes bestselling romance. When she pens a happily ever after, he kills off his entire cast. They're polar opposites. In fact, the only thing they have in common is that for the next three months, they're living in neighboring beach houses, broke, and bogged down with writer's block. Until, one hazy evening, one thing leads to another and they strike a deal designed to force them out of their creative ruts: Augustus will spend the summer writing something happy, and January will pen the next Great American Novel. She'll take him on field trips worthy of any rom-com montage, and he'll take her to interview surviving members of a backwoods death cult (obviously). Everyone will finish a book and no one will fall in love. But as the summer stretches on, January discovers a gaping plot hole in the story she's been telling herself about her own life, and begins to wonder what other things she might have gotten wrong, including her ideas about the man next door"--",
        "isbn": "9781984806734",
        "language": "en",
        "link": "https://books.google.com/books/about/Beach_Read.html?hl=&id=vDTgDwAAQBAJ",
        "pageCount": 384,
        "printType": "BOOK",
        "publishedDate": "2020",
        "thumbnail": "https://books.google.com/books/content?id=vDTgDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "Beach Read",
        "url": "https://books.google.com/books/about/Beach_Read.html?hl=&id=vDTgDwAAQBAJ",
      },
      {
        "authors": "Nichole Perkins",
        "categories": null,
        "dateFinished": "2021-12-03",
        "description": "A passionate, magnetic memoir that explores writer and podcast host Nichole Perkins's obsession with pop culture and the challenges of navigating relationships as a Black woman through feminism and Southern mores. Pop culture is the Pandora's Box of our lives. Racism, wealth, poverty, beauty, inclusion, exclusion, and hope -- all of these intractable and unavoidable features course through the media we consume. Examining pop culture's impact on her life, Nichole Perkins takes readers on a rollicking trip through the last twenty years of music, media and the internet from the perspective of one southern Black woman. She explores her experience with mental illness and how the TV series Frasier served as a crutch, how her role as mistress led her to certain internet message boards that prepared her for current day social media, and what it means to figure out desire and sexuality and Prince in a world where marriage is the only acceptable goal for women. Combining her sharp wit, stellar pop culture sensibility, and trademark spirited storytelling, Nichole boldly tackles the damage done to women, especially Black women, by society's failure to confront the myths and misogyny at its heart, and her efforts to stop the various cycles that limit confidence within herself. By using her own life and loves as a unique vantage point, Nichole humorously and powerfully illuminates how to take the best pop culture has to offer and discard the harmful bits, offering a mirror into our own lives.",
        "isbn": "9781538702741",
        "language": "en",
        "link": "https://books.google.com/books/about/Sometimes_I_Trip_on_How_Happy_We_Could_B.html?hl=&id=qD8czgEACAAJ",
        "pageCount": 256,
        "printType": "BOOK",
        "publishedDate": "2021-08-17",
        "thumbnail": "https://books.google.com/books/content?id=qD8czgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "title": "Sometimes I Trip on How Happy We Could Be",
        "url": "https://books.google.com/books/about/Sometimes_I_Trip_on_How_Happy_We_Could_B.html?hl=&id=qD8czgEACAAJ",
      },
      {
        "authors": "Matt Haig",
        "categories": [
          "Fiction",
        ],
        "dateFinished": "2021-12-09",
        "description": "The New York Times bestselling WORLDWIDE phenomenon Winner of the Goodreads Choice Award for Fiction | A Good Morning America Book Club Pick | Independent (London) Ten Best Books of the Year "A feel-good book guaranteed to lift your spirits."—The Washington Post The dazzling reader-favorite about the choices that go into a life well lived, from the acclaimed author of How To Stop Time and The Comfort Book. Somewhere out beyond the edge of the universe there is a library that contains an infinite number of books, each one the story of another reality. One tells the story of your life as it is, along with another book for the other life you could have lived if you had made a different choice at any point in your life. While we all wonder how our lives might have been, what if you had the chance to go to the library and see for yourself? Would any of these other lives truly be better? In The Midnight Library, Matt Haig's enchanting blockbuster novel, Nora Seed finds herself faced with this decision. Faced with the possibility of changing her life for a new one, following a different career, undoing old breakups, realizing her dreams of becoming a glaciologist; she must search within herself as she travels through the Midnight Library to decide what is truly fulfilling in life, and what makes it worth living in the first place.",
        "isbn": "9780525559481",
        "language": "en",
        "link": "https://play.google.com/store/books/details?id=nNjTDwAAQBAJ",
        "pageCount": 304,
        "printType": "BOOK",
        "publishedDate": "2020-09-29",
        "thumbnail": "https://books.google.com/books/content?id=nNjTDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "The Midnight Library",
        "url": "https://play.google.com/store/books/details?id=nNjTDwAAQBAJ",
      },
      {
        "authors": "Michael Pollan",
        "categories": [
          "Body, Mind & Spirit",
        ],
        "dateFinished": "2021-12-20",
        "description": "The instant New York Times bestseller “Expert storytelling . . . [Pollan] masterfully elevates a series of big questions about drugs, plants and humans that are likely to leave readers thinking in new ways.”—New York Times Book Review From #1 New York Times bestselling author Michael Pollan, a radical challenge to how we think about drugs, and an exploration into the powerful human attraction to psychoactive plants—and the equally powerful taboos. Of all the things humans rely on plants for—sustenance, beauty, medicine, fragrance, flavor, fiber—surely the most curious is our use of them to change consciousness: to stimulate or calm, fiddle with or completely alter, the qualities of our mental experience. Take coffee and tea: People around the world rely on caffeine to sharpen their minds. But we do not usually think of caffeine as a drug, or our daily use as an addiction, because it is legal and socially acceptable. So, then, what is a “drug”? And why, for example, is making tea from the leaves of a tea plant acceptable, but making tea from a seed head of an opium poppy a federal crime? In This Is Your Mind on Plants, Michael Pollan dives deep into three plant drugs—opium, caffeine, and mescaline—and throws the fundamental strangeness, and arbitrariness, of our thinking about them into sharp relief. Exploring and participating in the cultures that have grown up around these drugs while consuming (or, in the case of caffeine, trying not to consume) them, Pollan reckons with the powerful human attraction to psychoactive plants. Why do we go to such great lengths to seek these shifts in consciousness, and then why do we fence that universal desire with laws and customs and fraught feelings? In this unique blend of history, science, and memoir, as well as participatory journalism, Pollan examines and experiences these plants from several very different angles and contexts, and shines a fresh light on a subject that is all too often treated reductively—as a drug, whether licit or illicit. But that is one of the least interesting things you can say about these plants, Pollan shows, for when we take them into our bodies and let them change our minds, we are engaging with nature in one of the most profound ways we can. Based in part on an essay published almost twenty-five years ago, this groundbreaking and singular consideration of psychoactive plants, and our attraction to them through time, holds up a mirror to our fundamental human needs and aspirations, the operations of our minds, and our entanglement with the natural world.",
        "isbn": "9780593296905",
        "language": "en",
        "link": "https://books.google.com/books/about/This_Is_Your_Mind_on_Plants.html?hl=&id=Fxs3EAAAQBAJ",
        "pageCount": 288,
        "printType": "BOOK",
        "publishedDate": "2021-07-06",
        "thumbnail": "https://books.google.com/books/content?id=Fxs3EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "title": "This Is Your Mind on Plants",
        "url": "https://books.google.com/books/about/This_Is_Your_Mind_on_Plants.html?hl=&id=Fxs3EAAAQBAJ",
      },
    ]
  `);
});
