name: Uses a custom markdown template (`post-template`) and customizes the `posts-directory`, with a manual workflow trigger.

on:
  workflow_dispatch:
    inputs:
      date:
        description: Set a specific date to run the action (YYYY-MM-DD), leave blank for today.
        type: string

jobs:
  scheduled-post:
    runs-on: ubuntu-latest
    name: Write scheduled post
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write scheduled post
        uses: ./
        with:
          github-username: katydecorah
          github-repository: archive
          post-template: .github/actions/post-template-basic.md
          posts-directory: books/
          source-bookmarks: recipes|_data/recipes.json
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Commit files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "${{ env.title }}"
          git push
